### ISSUE TITLE
ProtocolException when running the tests

### ISSUE THREAD

**Issue by glyg** [ome/docker-example-omero-websockets#7]
Hi, trying to setup websockets and I get the following error on a fresh clone of the master branch

![Capture d’écran de 2021-03-16 17-40-48](https://user-images.githubusercontent.com/1426279/111346849-e91e2400-867e-11eb-93c7-04a1692d544f.png) 

(sorry I could not copy/paste the traceback from the server)

I get reach the webclient with http

Output of uname -a:
```bash
 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 
```

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.5, build unknown

I get a `Ice.ConnectionRefusedException` exception when trying to log through the python API with 

`conn = BlitzGateway(host="localhost", port="4064", username="root", passwd="omero")`

I have no issues with the standard docker-compose from https://github.com/ome/docker-example-omero

I do not seem to have SElinux active, though I'm not sure how to check that (no service is running as far as I can tell)

Any advice on how to debug that further?

**Comment by joshmoore** [comment]
Hi @glyg,

The "bad gateway" most likely implies that the `omeroweb` container sitting behind the `nginx` container has some issue. I was worried that this might be due to a change in dependencies so I ran locally:

```
docker-compose pull
bash test.sh
```

and got:

```
================================================== 26 passed, 138 warnings in 12.13s ==================================================
```

so I *think* the repo is ok. Can you check the logs for the omero-web container?

```
$ docker-compose logs omeroweb
...
omeroweb_1     | Post-processed 'omeroweb.viewer.min.css' as 'omeroweb.viewer.min.css'
omeroweb_1     | Post-processed 'omeroweb.viewer.min.js' as 'omeroweb.viewer.min.js'
omeroweb_1     |
omeroweb_1     | 723 static files copied to '/opt/omero/web/OMERO.web/var/static', 2 post-processed.
omeroweb_1     | Clearing expired sessions. This may take some time... [OK]
omeroweb_1     | [2021-03-17 10:25:50 +0000] [59] [INFO] Starting gunicorn 20.0.4
omeroweb_1     | [2021-03-17 10:25:50 +0000] [59] [INFO] Listening at: http://0.0.0.0:4080 (59)
omeroweb_1     | [2021-03-17 10:25:50 +0000] [59] [INFO] Using worker: sync
omeroweb_1     | [2021-03-17 10:25:50 +0000] [62] [INFO] Booting worker with pid: 62
omeroweb_1     | [2021-03-17 10:25:50 +0000] [64] [INFO] Booting worker with pid: 64
omeroweb_1     | [2021-03-17 10:25:50 +0000] [65] [INFO] Booting worker with pid: 65
omeroweb_1     | [2021-03-17 10:25:50 +0000] [66] [INFO] Booting worker with pid: 66
omeroweb_1     | [2021-03-17 10:25:50 +0000] [70] [INFO] Booting worker with pid: 70
```

```
$ docker-compose exec omeroweb cat /opt/omero/web/OMERO.web/var/log/OMEROweb.log
...
2021-03-17 10:26:44,917  INFO [                omeroweb.webclient.views] (proc.00064) <module>():113 INIT '64'
2021-03-17 10:26:44,921  INFO [                                    root] (proc.00064) process_custom_settings():1010 Processing custom settings for module omeroweb.api.api_settings
2021-03-17 10:26:44,924  INFO [                                    root] (proc.00064) process_custom_settings():1010 Processing custom settings for module omero_iviewer.iviewer_settings
2021-03-17 10:26:45,011  INFO [                                    root] (proc.00064) process_custom_settings():1010 Processing custom settings for module omero_mapr.mapr_settings
2021-03-17 10:26:45,015  INFO [                                    root] (proc.00064) process_custom_settings():1010 Processing custom settings for module omero_parade.parade_settings
```

**Comment by glyg** [comment]
Thanks Josh, I'll investigate this &mdash; I was not aware of the `pull` command, so maybe I am running an older image for omeroweb. I'll try this out tomorrow morning,

**Comment by glyg** [comment]
The tests are passing after a docker-compose pull  - sorry for the noise

**Comment by joshmoore** [comment]
Glad to hear it.
